// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: languages.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getLanguageIDByName = `-- name: GetLanguageIDByName :one
SELECT id
FROM languages
WHERE language = $1
`

func (q *Queries) GetLanguageIDByName(ctx context.Context, language string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getLanguageIDByName, language)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
