// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Role struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type User struct {
	ID         uuid.UUID      `json:"id"`
	Email      string         `json:"email"`
	IsActive   sql.NullBool   `json:"is_active"`
	Handle     string         `json:"handle"`
	FirstName  sql.NullString `json:"first_name"`
	LastName   sql.NullString `json:"last_name"`
	Bio        sql.NullString `json:"bio"`
	AvatarUrl  sql.NullString `json:"avatar_url"`
	IsVerified sql.NullBool   `json:"is_verified"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}
