// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Language struct {
	ID       uuid.UUID `json:"id"`
	Language string    `json:"language"`
}

type Role struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type Server struct {
	ID          uuid.UUID      `json:"id"`
	OwnerID     uuid.UUID      `json:"owner_id"`
	ServerName  string         `json:"server_name"`
	Description sql.NullString `json:"description"`
	IconUrl     sql.NullString `json:"icon_url"`
	BannerUrl   sql.NullString `json:"banner_url"`
	IsPublic    sql.NullBool   `json:"is_public"`
	MemberCount sql.NullInt32  `json:"member_count"`
	ServerLevel sql.NullInt32  `json:"server_level"`
	MaxMembers  sql.NullInt32  `json:"max_members"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
	InviteCode  string         `json:"invite_code"`
}

type TextChannel struct {
	ID          uuid.UUID    `json:"id"`
	OwnerID     uuid.UUID    `json:"owner_id"`
	ServerID    uuid.UUID    `json:"server_id"`
	LanguageID  uuid.UUID    `json:"language_id"`
	ChannelName string       `json:"channel_name"`
	LastActive  sql.NullTime `json:"last_active"`
	IsLocked    sql.NullBool `json:"is_locked"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
}

type TextMessage struct {
	ID        uuid.UUID      `json:"id"`
	OwnerID   uuid.UUID      `json:"owner_id"`
	ChannelID uuid.UUID      `json:"channel_id"`
	Message   string         `json:"message"`
	Image     sql.NullString `json:"image"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type User struct {
	ID         uuid.UUID      `json:"id"`
	Email      string         `json:"email"`
	Password   sql.NullString `json:"password"`
	IsActive   sql.NullBool   `json:"is_active"`
	Handle     string         `json:"handle"`
	FirstName  sql.NullString `json:"first_name"`
	LastName   sql.NullString `json:"last_name"`
	Bio        sql.NullString `json:"bio"`
	AvatarUrl  sql.NullString `json:"avatar_url"`
	IsVerified sql.NullBool   `json:"is_verified"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type UserRole struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

type UserServer struct {
	UserID   uuid.UUID `json:"user_id"`
	ServerID uuid.UUID `json:"server_id"`
	Role     string    `json:"role"`
}

type VoiceChannel struct {
	ID          uuid.UUID    `json:"id"`
	OwnerID     uuid.UUID    `json:"owner_id"`
	ServerID    uuid.UUID    `json:"server_id"`
	LanguageID  uuid.UUID    `json:"language_id"`
	ChannelName string       `json:"channel_name"`
	ChannelID   string       `json:"channel_id"`
	LastActive  sql.NullTime `json:"last_active"`
	IsLocked    sql.NullBool `json:"is_locked"`
	CreatedAt   time.Time    `json:"created_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
}

type VoiceChannelMember struct {
	UserID    uuid.UUID `json:"user_id"`
	ChannelID uuid.UUID `json:"channel_id"`
	ServerID  uuid.UUID `json:"server_id"`
}
