// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user_servers.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUserServer = `-- name: CreateUserServer :one
INSERT INTO user_servers (user_id, server_id)
VALUES ($1, $2)
RETURNING user_id, server_id
`

type CreateUserServerParams struct {
	UserID   uuid.UUID `json:"user_id"`
	ServerID uuid.UUID `json:"server_id"`
}

func (q *Queries) CreateUserServer(ctx context.Context, arg CreateUserServerParams) (UserServer, error) {
	row := q.db.QueryRowContext(ctx, createUserServer, arg.UserID, arg.ServerID)
	var i UserServer
	err := row.Scan(&i.UserID, &i.ServerID)
	return i, err
}
